# Upptime configuration for Negev Shelter Access Analysis
# https://upptime.js.org/docs/configuration

owner: NegevUrbanResearch
repo: upptime
sites:
  - name: Shelter Access Main Site
    url: https://negevurbanresearch.github.io/shelter_access/
    icon: 🏠
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000

  - name: Data API - Buildings
    url: https://negevurbanresearch.github.io/shelter_access/data/buildings_light.geojson
    icon: 🏗️
    expectedStatusCodes:
      - 200
    maxResponseTime: 10000

  - name: Data API - Shelters
    url: https://negevurbanresearch.github.io/shelter_access/data/shelters.geojson
    icon: 🛡️
    expectedStatusCodes:
      - 200
    maxResponseTime: 10000

  - name: Data API - Accessibility Heatmap
    url: https://negevurbanresearch.github.io/shelter_access/data/accessibility_heatmap.json
    icon: 🗺️
    expectedStatusCodes:
      - 200
    maxResponseTime: 10000

status-website:
  cname: status.negevurbanresearch.org # Optional: Custom domain
  logoUrl: https://negevurbanresearch.github.io/shelter_access/data/favicon.ico
  name: Shelter Access Status
  introTitle: "Negev Shelter Access Monitoring"
  introMessage: Real-time status monitoring for the Negev Shelter Access Analysis platform
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Main Site
      href: https://negevurbanresearch.github.io/shelter_access/

# Notification settings
notifications:
  - type: slack
    webhook-url: $SLACK_WEBHOOK_URL # Add your Slack webhook if needed

# Workflow schedule - check every 5 minutes
schedule: "*/5 * * * *"

# GitHub options
user-agent: upptime
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Commit messages
commitMessages:
  readmeContent: ":pencil: Update summary in README [skip ci] [upptime]"
  summaryJson: ":card_file_box: Update status summary [skip ci] [upptime]"
  statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms) [skip ci] [upptime]"
  graphsUpdate: ":bento: Update graphs [skip ci] [upptime]"
  staticSite: ":arrow_up: Update @upptime to $VERSION"
  allUp: ":green_heart: All sites are up"
